### ISSUE TITLE
Support AWS Fargate

### ISSUE THREAD

**Issue by dsperling** [smithmicro/jmeter-ecs#12]
https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-aws-fargate-a-technology-to-run-containers-without-managing-infrastructure/

Fargate will allow us to run JMeter in with the following benefits:
* Instances charged by the second instead of by the hour
* Eliminate the need for selecting appropriate instance types

Fargate is only available in N. VIrginia at the moment...

**Comment by dsperling** [comment]
It appears that Fargate does not allow you to create instances that have ssh access using a Key Pair.  Currently this project requires the use of scp and ssh to communicate between Lucy and Gru.  

A re-design would be required, for example, to jave Gru to pick up the source .jmx file from a S3 bucket, and then deliver the results files back to S3.

**Comment by dsperling** [comment]
No plans to move to Fargate.

**Comment by iskren-dimov** [comment]
Any change of plans here? It would be a lot easier to use this implementation if Fargate is supported.
