### ISSUE TITLE
The minion instances are not recognized

### ISSUE THREAD

**Issue by Kostanos** [smithmicro/jmeter-ecs#17]
trying to run the lucy docker, and got the issue with detecting Minion and Gru instances, in my case, all 3 instances detected as Gru and no minions at all:

```
...
lucy_1  | Gru instance ID: i-**********
lucy_1  | i-*********
lucy_1  | i-**********
lucy_1  | Minion instances IDs: 
lucy_1  | Gru at **.***.***.*****.**.**.****.***.***.***
...
```
For some reason there were no instance with running task.
Is there any other way to determinate Gru vs Minion than by tasks count? as it expects in code:
```
...
# Step 4 - Get Gru and Minion's instance ID's.  Gru is the container with a runningTasksCount = 0
...
```

**Comment by dsperling** [comment]
I just duplicated this.  You can check to see if you are having the same problem I am by looking at your jmeter cloudwatch logs.  You should see this:
```
Detecting an AWS Environment
Using Minion AWS Public HOSTNAME ec2-54-202-119-110.us-west-2.compute.amazonaws.com
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /logs/hs_err_pid22.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Out of memory' (errno=12)
```
If the Minions run out of memory, the containers exit.  Therefore the Step 4 sees all instances with a `runningTasksCount = 0`

I will look into this.  It could be that the ecs-agent running in the instance got larger and our requested memory in the minion.yml file is not available:
```
version: '2'

services:
  minion:
    image: smithmicro/jmeter:latest
    mem_limit: 950m
    ports:
    ...
```

**Comment by dsperling** [comment]
It turns out this broke when we added support for JMeter 4.0.  For a temporary workaround, use version 3.3 of JMeter by adding this to your Lucy `docker run` command line:
```
--env JMETER_VERSION=3.3
```

**Comment by Kostanos** [comment]
I couldn't found any Cloudwatch logs also /logs folder is empty.
did you configured the cloudwatch logs in lucy.yml?
So far, if I make instances bigger and add bigger memory limit it should work with 4.0 right?
Will try it now

**Comment by Kostanos** [comment]
Just to confirm, with `--env JMETER_VERSION=3.3` works as expected.

Thank you!

**Comment by dsperling** [comment]
Added lines to the entrypoint script to adjust the JAVA HEAP.
