### ISSUE TITLE
Feature request: Delete CloudFormation stack only if RETAIN_CLUSTER flag is absent

### ISSUE THREAD

**Issue by Kostanos** [smithmicro/jmeter-ecs#18]
Running multiples times the same or similar tests takes a time to recreate the environment.
Would be great to have the feature to indicate which part of environment we like to re-create.

We can cover with this:
```
RECREATE_CLOUDFORMATION
RECREATE_CLUSTER_INSTANCES
etc..
```

**Comment by dsperling** [comment]
We have considered this, but recently have been looking at supporting Fargate.  See #12.

Fargate supports billing my the minute vs by the hour, which would be a perfect match for JMeter.

**Comment by Kostanos** [comment]
EC2 instances are available for pay per second (min 60 seconds) already.
So I assume switching to Fargate only may improve the instances initialization time (hope it makes it faster), but actually not to costs or I missed something here?

**Comment by dsperling** [comment]
I had forgotten AWS made the per-minute change in October.

The two main benefits would be speed and flexibility.  Cluster initialization would be faster, and we would no longer need to specify an instance type.  Currently, we have to match memory size used via the docker-compose.yml file and the instance type.

However, Fargate will increase the complexity of Lucy's job.  Lucy makes heavy use of the `aws ec2 describe-instances` CLI API which no longer functions, so this is a re-design.

Now with AWS Per-minute pricing, maybe it makes more sense to implement this suggestion first.

**Comment by dsperling** [comment]
I have a solution ready for test.  You can use `smithmicro/lucy:feature-18` and pass `--env CLUSTER_DELETE=false` on the docker run command line.

This new `CLUSTER_DELETE` environment variable simply skips the `ecs-cli down --cluster $CLUSTER_NAME --force` command in Lucy's script.  The beginning of the script was modified to detect if the cluster is already running and checks to see if the instance count is the same.  If so, it skips the create step.  If the requested MINION_COUNT is different the cluster is re-created, or it creates the cluster if it does not exist.

**Comment by dsperling** [comment]
I have pushed the changes so you can now do `RETAIN_CLUSTER` tests with `smithmicro/lucy:latest`.  I will keep this open until you can confirm everything is working as expected.

**Comment by Kostanos** [comment]
I think is missing to update the task definition in the service.
I run it few times, and all the time it uses the same task definition version.

**Comment by dsperling** [comment]
Updating the Task Definition is the job of `ecs-cli`.  During the `ecs-cli compose --file /opt/jmeter/lucy.yml up --cluster $CLUSTER_NAME` Lucy step, the tool will decide to bump the Task definition version if the contents of lucy.yml change.  Sometimes I have seen it bump the version without any changes to lucy.yml.  I am unsure why that is.

Does that help?

**Comment by Kostanos** [comment]
works perfect. Thank you  for the feature!
