### ISSUE TITLE
How to add SSL p12 file to Jmeter? 

### ISSUE THREAD

**Issue by xianing1977** [smithmicro/jmeter-ecs#22]
My test server request SSL connection, that need p12 file. 
When I run Jmeter locally, I must change system.properties and add javax.net.ssl.keyStore=xxxxx.p12. 
How to add my certificate file xxxx.p12 and system.properties files to Jmeter?

**Comment by dsperling** [comment]
Closing and using #24 as driving ticket.

**Comment by hdleviathan** [comment]
> My test server request SSL connection, that need p12 file.
> When I run Jmeter locally, I must change system.properties and add javax.net.ssl.keyStore=xxxxx.p12.
> How to add my certificate file xxxx.p12 and system.properties files to Jmeter?
 
Hi @xianing1977 , just wondering if you've resolved this issue. I am currently facing the same problem.
