### ISSUE TITLE
Sample send mode

### ISSUE THREAD

**Issue by psywolf85** [smithmicro/jmeter-ecs#28]
In the current constellation, when there are to many clients, the bandwith is eaten up by samples that are being sent to the server.
Samples can not reach the server in time, so the client is slowing down the test, because he waits until the server received the sample.

To fix that, another sendermode has to be set. For example disk or async.
https://jmeter.apache.org/usermanual/remote-test.html#sendermode

**Comment by dsperling** [comment]
@psywolf85 do you have a jmx file that can duplicate the problem?

**Comment by dsperling** [comment]
Now supported in v2.4 along with JMeter 5.  Fixed #23 to make this now operational.

Pass the following in the Lucy Docker run command:

`--env JMETER_FLAGS='-Dmode=Asynch'`
