### ISSUE TITLE
Support newer Plugin Manager

### ISSUE THREAD

**Issue by dsperling** [smithmicro/jmeter-ecs#31]
Current included version is 0.19.  Include support for 0.20.

**Comment by undera** [comment]
Why not 1.3?

**Comment by dsperling** [comment]
Yes, we will support 1.3.  Do you know if there is a page explaining which Jmeter versions that the plugin manager is compatible with?  We want to keep the 2.0 and 3.x Jmeter images current.

**Comment by undera** [comment]
There is no such page. Plugins Manager 1.3 supports JMeter 2.13+
