### ISSUE TITLE
how pass jmx  dependency testing image and csv file

### ISSUE THREAD

**Issue by vignesLYM** [smithmicro/jmeter-ecs#40]
Hi ,

Please tell me how pass jmx  dependency related testing image and csv file do docker

**Comment by dsperling** [comment]
See the `COPY_DIR` environment variable.

There is a sample JMX here:
https://github.com/smithmicro/jmeter-ecs/blob/master/plans/demo-csv.jmx

**Comment by vignesLYM** [comment]
Hi smith actually i used your demo-csv.jmx and search-strings.csv file in my container,  csv and jmx files i also moved container path is  /plans <- folder. but not giveing output please tell me where i am doing wrong.

my updated code is 
------------------------------
# Step 6 - Copy all files to Minions/Gru, or just the JMX
  echo "Step 6 - Copy all files to Minions/Gru, or just the JMX"
  if [ "$COPY_DIR" == '' ]; then
    echo "Copying $INPUT_JMX to Gru"
	
     scp -i $PEM_PATH/$KEY_NAME.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /var/www/html/jmeter-ecs-master/plans/* ec2-user@${GRU_HOST}:/tmp
  


 showing  output :

**Starting the test @ Fri Mar 22 13:36:22 GMT 2019 (1553261782273)
summary =      0 in 00:00:00 = ******/s Avg:     0 Min: 9223372036854775807 Max: -9223372036854775808 Err:     0 (0.00%)
Tidying up remote @ Fri Mar 22 13:36:25 GMT 2019 (1553261785524)
Exiting remote servers
summary =      0 in 00:00:00 = ******/s Avg:     0 Min: 9223372036854775807 Max: -9223372036854775808 Err:     0 (0.00%)
Tidying up remote @ Fri Mar 22 13:36:25 GMT 2019 (1553261785621)
Exiting remote servers
Remote engines have been started
Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445
summary =      0 in 00:00:00 = ******/s Avg:     0 Min: 9223372036854775807 Max: -9223372036854775808 Err:     0 (0.00%)
Tidying up remote @ Fri Mar 22 13:36:25 GMT 2019 (1553261785732)**

**Comment by vignesLYM** [comment]
done...
