### ISSUE TITLE
how set jmeter ramp up period here

### ISSUE THREAD

**Issue by vignesLYM** [smithmicro/jmeter-ecs#41]
how set jmeter ramp up period here

**Comment by dsperling** [comment]
Ramp-Up Period is a configuration in your JMX file.  Nothing for Gru or Lucy to do here.

See Ramp-Up Period in this screens shot:
http://jmeter.apache.org/usermanual/component_reference.html#Thread_Group

**Comment by vignesLYM** [comment]
Thank you
