### ISSUE TITLE
The Gui generated jtl file ,the JTL report showing No data to display in view results tree

### ISSUE THREAD

**Issue by vignesLYM** [smithmicro/jmeter-ecs#43]
we are facing the following challenges using JMeter docker kindly give your feedback

1. Save response to a file the file which has been stored in HTML format in slave server when errors are occurring.
2. The Gui generated jtl file, the JTL report showing No data to display in view results tree
3. The failed request response time and request count is showing wrong in Aggregate report in JMeter using JTL output file.
4. After successfully download the report, When we click on index HTML report it is showing wrong details for the following graphs.

    a. Response Times Over Time
    b. Response Time Percentiles Over Time (successful responses)
    c. Active Threads Over Time
    d. Bytes Throughput Over Time
    e. Latencies Over Time
     f. Connect Time Over Time
    g. Hits Per Second
    h. Codes Per Second

**Comment by dsperling** [comment]
Do you have a sample .JMX file you can share the reproduces the problem?

**Comment by vignesLYM** [comment]
i will try again one time and let you ..
