### ISSUE TITLE
Unable to run more than 10 minion tasks

### ISSUE THREAD

**Issue by neilgroat** [smithmicro/jmeter-ecs#6]
There is a ECS limit that restricts a single run-task command to have a maximum count of 10

Adding in the ability to break the command up if there are more than 10 minions would be helpful when a load test requires high volume.

**Comment by neilgroat** [comment]
Possibly something like this?

# Step 6 - Run the Minion task with the requested count
echo "Running task: $MINION_TASK_DEFINITION, instance count: $MINION_COUNT"
if [ $MINION_COUNT -lt 10 ]
MINION_TASK_IDS=$(aws ecs run-task --cluster $MINION_CLUSTER_NAME --task-definition $MINION_TASK_DEFINITION --count $MINION_COUNT \
  --query 'tasks[*].[taskArn]' --output text | tr '\n' ' ')
else
	i=0
	while [ $i -lt $MINION_COUNT ]
	do
		MINION_TASKS_IDS="$MINION_TASKS_IDS$(aws ecs run-task --cluster $MINION_CLUSTER_NAME --task-definition $MINION_TASK_DEFINITION --count 1 \
		--query 'tasks[*].[taskArn]' --output text | tr '\n' ' ')"
		let "i++"
	done
fi

**Comment by dsperling** [comment]
Thanks for finding this.  Here is the reference to all ECS service limits.

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_limits.html
